Update html-quiz.md
Ebazhanov/linkedin-skill-assessments-quizzes pull request #1130
Opened 2021-02-11 16:54 UTC by retr00exe

Add 2 questions about `<video>` tag and empty element.
Ref: 
[Screenshoot Q63](https://res.cloudinary.com/retr00exe/image/upload/v1613062060/Screenshot_951_harncv.png)
[Screenshoot Q64](https://res.cloudinary.com/retr00exe/image/upload/v1613062060/Screenshot_952_m2yvko.png)

I also answer both the question, here's some proof from the HTML documentation, CMIIW
[Answer Q63 (w3schools)](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_video)
[Answer Q64 (MDN Web Docs)](https://developer.mozilla.org/en-US/docs/Glossary/Empty_element)

2021-02-11 17:48 UTC, Ebazhanov requested changes
Amazing job :+1: @retr00exe! But before we merge it I would like to ask you to transfer screenshot and reference link inside the *.md file, this way we can keep them for other people! If you need my help please let me know!

2021-02-11 18:57 UTC, retr00exe commented
Hi, @Ebazhanov thanks for reviewing my works I really appreciate it. Did you mean add the screenshot image to *.md file? Or just add the screenshot links to *.md file? I'm a little bit confused 😅

2021-02-11 20:08 UTC, Ebazhanov commented
> Hi, @Ebazhanov thanks for reviewing my works I really appreciate it. Did you mean add the screenshot image to *.md file? Or just add the screenshot links to *.md file? I'm a little bit confused 😅

No worries, yes you can add both screenshot and links see example here
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/machine-learning/machine-learning-quiz.md
let me know if you need any help from me

2021-02-11 20:47 UTC, retr00exe commented
Oh I see, but there's nothing special about my screenshot, it just the screenshot of plain question without any important picture in it, the reason why I add the screenshot references to this PR is because I just want to confirm that my question is legit from linkedin, so should I add it too to *.md file?

2021-02-12 07:41 UTC, Ebazhanov commented
> Oh I see, but there's nothing special about my screenshot, it just the screenshot of plain question without any important picture in it, the reason why I add the screenshot references to this PR is because I just want to confirm that my question is legit from linkedin, so should I add it too to *.md file?

Ahh got it! yes, in this case please add only links without screenshots and we will merge it immediatly, thank you @retr00exe and have a good day!

2021-02-12 09:25 UTC, Ebazhanov approved these changes
Perfect :hibiscus:! Approved and merged
Thank you, @retr00exe :punch:

2021-02-12 09:25 UTC, merged

2021-02-12 09:26 UTC, Ebazhanov commented
@all-contributors please add @retr00exe for design, code