Support noat.cards
Ebazhanov/linkedin-skill-assessments-quizzes pull request #1341
Opened 2021-03-27 16:34 UTC by kevintruong

Hi, 

I think it will be great to native support noat.cards 
The service will help people on quick create quiz competition game

2021-03-28 21:24 UTC, Ebazhanov requested changes
Thank you, @kevintruong, for bringing this interesting idea! I think we have to try it out, but I would prefer if you will clone my repo and will create on your https://github.com/noatcards
or on my here https://github.com/linkedin-faq (I can give you access by request)
this way we will not change this repo and will not display this unknown weird strings everywhere

```
+++
noatcards = True
isdraft = False
+++
```
What do you think? If you have father questions please DM me here https://discord.com/invite/jWyDVX3e4w

2021-03-29 00:46 UTC, kevintruong commented
Hi @Ebazhanov  , What do you think about a declare file for noat.cards in your repo. 
We will have yaml file call .noatcards.yaml which will declare all quiz file. Then my service can import the repo. 
This way, we don't need to push the header 
```
+++
noatcards = True
isdrafe = False
+++
``` 
in every quiz file (*.md) in the system. 
Do you think this way will better to the merge ?

2021-03-29 07:17 UTC, Ebazhanov commented
> Hi @Ebazhanov , What do you think about a declare file for noat.cards in your repo.
> We will have yaml file call `.noatcards.yaml` in root which will declare all quiz file. Then my service can import the repo.
> This way, we don't need to push the header
> 
> ```
> +++
> noatcards = True
> isdrafe = False
> +++
> ```
> 
> in every quiz file (*.md) in your repo.
> Do you think this way will better to the merge ?


@kevintruong first let's create POC example

2021-03-29 07:18 UTC, kevintruong commented
Deal

2021-03-29 13:49 UTC, monkrus commented
> Deal
@kevintruong Are you planning on monetizing your telegram bot?

2021-03-29 13:52 UTC, kevintruong commented
> > Deal
> > @kevintruong Are you planning on monetizing your telegram bot?

Yes and No  
I am thinking about open source model here rather than monetizing the bot.

2021-03-29 16:02 UTC, kevintruong commented
```|
---
type: "noatcards"
root_dir: "./"
content:
  - file: "c++/quiz_c++.md"
    isdraft: True
  - file: "aws/quiz_aws.md"
    isdraft: True
  - file: "gcp/quiz_gcp.md"
    # default isdraft is False
```
@Ebazhanov  please take a look. 
POC for `.noatcards.yaml`

2021-03-30 00:23 UTC, monkrus commented
> > > Deal
> > > @kevintruong Are you planning on monetizing your telegram bot?
> 
> Yes and No
> I am thinking about open source model here rather than monetizing the bot.

Got it. However, it is an option we can all discuss.

2021-03-30 15:14 UTC, kevintruong commented
hi @Ebazhanov would you please to give me some comment about the POC above ?

2021-03-31 17:02 UTC, Ebazhanov approved these changes
Very nice! Go ahead! 👍

2021-03-31 17:03 UTC, merged