added 4 new questions,  there were a repeat of two questions for ques…
Ebazhanov/linkedin-skill-assessments-quizzes pull request #1385
Opened 2021-04-04 17:09 UTC by swordwielder

…tion Q5 and question Q11, removed both of them and fixed the numbering

2021-04-04 17:56 UTC, Ebazhanov requested changes
Left some comments @swordwielder BTW great job!

2021-04-04 17:56 UTC, Ebazhanov commented on nosql/nosql-quiz.md
> -#### Q24. You need to implement the simples possible scalable, in-memory cache for your AWS application. Which service do you select?
sorry but what is the reason of removing this test? I can't find any related duplication FYI

2021-04-04 17:56 UTC, Ebazhanov commented on nosql/nosql-quiz.md
> + #### Q43. Which statement retrieves an item from the MusicCollection table in DynamoDB?
```suggestion
#### Q43. Which statement retrieves an item from the MusicCollection table in DynamoDB?
```

2021-04-04 17:56 UTC, Ebazhanov commented on nosql/nosql-quiz.md
> + #### Q44. Database availability is measured by which metric?
```suggestion
#### Q44. Database availability is measured by which metric?
```

2021-04-04 17:56 UTC, Ebazhanov commented on nosql/nosql-quiz.md
> +  #### Q44. You need to encrypt data at rest in DynamoDB.  Which action do you take?
```suggestion
 #### Q44. You need to encrypt data at rest in DynamoDB.  Which action do you take?
```

2021-04-05 23:37 UTC, swordwielder reviewed
please check with Question, there was a spelling error with that one too but the choice are the same.

2021-04-06 06:26 UTC, Ebazhanov commented on nosql/nosql-quiz.md
> -#### Q24. You need to implement the simples possible scalable, in-memory cache for your AWS application. Which service do you select?
ahh, ok I see it now, good finding! FYI there is only different answers :grimacing:

2021-04-06 06:30 UTC, Ebazhanov approved these changes
Thanks, @swordwielder great improvements!

2021-04-06 06:30 UTC, merged