[Linux] Add answers Q78 to Q81
Ebazhanov/linkedin-skill-assessments-quizzes pull request #3378
Opened 2022-03-26 15:48 UTC by pestadieu

Fixes #3229 

Ping @D4RIO @Amsal1 
I am unsure about the answer to Q81. It would be nice if one of you could double check that.

2022-03-27 06:06 UTC, D4RIO requested changes
Thank you for your collaboration, and for pinging us for review. The 81 should be the last option. See, fdisk -l will indeed read the contents of /proc/partitions if you don’t provide an argument, but to get partitions from there, and then it will read each table. The output of fdisk -l is a lot when compared to /proc/partitions.

2022-03-29 17:59 UTC, its0x08 approved these changes

2022-04-03 14:59 UTC, Ebazhanov approved these changes
Hello, @pestadieu! Thank you for your great input! 👍

2022-04-03 14:59 UTC, merged

2022-04-03 14:59 UTC, Ebazhanov commented
@all-contributors please add @pestadieu for design, code