New phrasing Q114 + 2 new questions (with answers)
Ebazhanov/linkedin-skill-assessments-quizzes pull request #3920
Opened 2022-06-28 22:32 UTC by Knackii

No, last choice of Q115 is not a typo from me.

2022-06-29 20:40 UTC, sathir requested changes

2022-06-29 20:40 UTC, sathir commented on microsoft-excel/microsoft-excel-quiz.md
> +(missing screenshot)
Better to add the screenshot

2022-07-01 14:10 UTC, Knackii commented on microsoft-excel/microsoft-excel-quiz.md
> +
It's litteraly just "=(8+2*3)/7"

2022-07-01 14:10 UTC, Knackii commented on microsoft-excel/microsoft-excel-quiz.md
> +(missing screenshot)
I don't have it

2022-07-02 06:12 UTC, Ebazhanov approved these changes
Thank you @Knackii for your great input! 🌹

2022-07-02 06:12 UTC, merged

2022-07-02 06:12 UTC, Ebazhanov commented
@all-contributors please add @Knackii for design, code