Update c-quiz.md
Ebazhanov/linkedin-skill-assessments-quizzes pull request #4586
Opened 2022-10-06 10:00 UTC by tripathisharad

Hi I have added a c programming question please add it with hacktoberfest accepted tag thankyou.

2022-10-06 20:47 UTC, Ebazhanov requested changes
@tripathisharad left comments

2022-10-06 20:47 UTC, Ebazhanov commented on c-(programming-language)/c-quiz.md
> + #### Q70. What will be the output of the following code snippet?
```suggestion
 #### Q70. What will be the output of the following code snippet?
```

2022-10-06 20:47 UTC, Ebazhanov commented on c-(programming-language)/c-quiz.md
> +output --
```suggestion
 #include <stdio.h>  
void change(int,int);  
int main()  
{  
    int a=10,b=20;  
    change(a,b); //calling a function by passing the values of variables.  
    printf("Value of a is: %d",a);  
    printf("\n");  
    printf("Value of b is: %d",b);  
    return 0;  
}  
void change(int x,int y)  
{  
    x=13;  
    y=17;  
}  

output --
```
you have to put this code inside backtick to make it properly visible in *.md file

2022-10-06 20:47 UTC, Ebazhanov commented on c-(programming-language)/c-quiz.md
> +[4.]20,10
this is not typical format for quiz answers, please take a look at examples, thanks

2022-10-06 21:31 UTC, tripathisharad reviewed
Hi I have resolved all the issue now please merge it, and if there anything else then please let me know thankyou.

2022-10-06 21:33 UTC, tripathisharad commented
Hi @Ebazhanov I have arranged the fields as you suggested thanks for your support. Please merge it with hacktoberfest thankyou.

2022-10-07 20:19 UTC, Ebazhanov requested changes
@tripathisharad can you also please resolve merge conflicts, thanks

2022-10-13 15:50 UTC, Ebazhanov commented
@tripathisharad ping

2022-10-13 16:10 UTC, tripathisharad commented
I have checked everything is ok thank you

2022-10-13 16:12 UTC, closed without merging