Update mysql-quiz.md
Ebazhanov/linkedin-skill-assessments-quizzes pull request #4587
Opened 2022-10-06 10:12 UTC by tripathisharad

Hi I have added a new mysql question please add it with hacktoberfest and hacktoberfest accepted tag.

2022-10-06 13:28 UTC, GTekSD approved these changes

2022-10-06 20:51 UTC, Ebazhanov requested changes
@tripathisharad left comments

2022-10-06 20:51 UTC, Ebazhanov commented on mysql/mysql-quiz.md
> +  WHERE title=’HEAD TELLER’;
```suggestion
  SELECT emp_id, fname, lname
  FROM employee
  WHERE title=’HEAD TELLER’;
```
i would prefer if you put this code inside backtick to format it

2022-10-06 20:51 UTC, Ebazhanov commented on mysql/mysql-quiz.md
> +  WHERE title=’HEAD TELLER’ AND start_date&gt;2008-11-23;
please look at other quizes how there formatted task inside question

2022-10-06 20:51 UTC, Ebazhanov commented on mysql/mysql-quiz.md
> +  ON e.dept_id=e.dept_id;
dito

2022-10-06 21:44 UTC, tripathisharad reviewed
I have resolved the issue please check it once thankyou.

2022-10-07 20:20 UTC, Ebazhanov approved these changes
LGTM, thank you @tripathisharad 👍

2022-10-07 20:20 UTC, merged

2022-10-07 20:21 UTC, Ebazhanov commented
@all-contributors please add @tripathisharad for design, code