Update python-quiz.md
Ebazhanov/linkedin-skill-assessments-quizzes pull request #4589
Opened 2022-10-06 10:54 UTC by tripathisharad

Hi I have recently encountered with this question and I have not found the solution in above code hence I have added it

2022-10-06 13:22 UTC, GTekSD approved these changes

2022-10-06 15:39 UTC, tripathisharad commented on python/python-quiz.md
> +
Hi I have explained the solution thankyou.

2022-10-06 16:04 UTC, GTekSD approved these changes

2022-10-06 16:04 UTC, GTekSD commented on python/python-quiz.md
> +
Good Job!

2022-10-06 16:35 UTC, tripathisharad commented on python/python-quiz.md
> +
Hello @GTekSD please merge the request with Hacktoberfest and Hacktoberfest accepted thankyou.

2022-10-07 20:26 UTC, Ebazhanov requested changes
@tripathisharad pls resolve merge conflicts, thanks

2022-10-12 21:48 UTC, Ebazhanov commented
Please @tripathisharad fix merge conflicts because someone people already making PR based on your changes: https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4726

2022-10-13 16:07 UTC, closed without merging