New questions and answers
Ebazhanov/linkedin-skill-assessments-quizzes pull request #4649
Opened 2022-10-09 02:00 UTC by victorwlin

2022-10-10 20:05 UTC, Ebazhanov requested changes
Hello, @victorwlin! Thanks for PR, can you please improve formatting for links, thanks

2022-10-10 20:05 UTC, Ebazhanov commented on accounting/accounting-quiz.md
> +> [Reference](https://www.investopedia.com/terms/c/currentliabilities.asp)
```suggestion
[Reference](https://www.investopedia.com/terms/c/currentliabilities.asp)
```

2022-10-10 20:05 UTC, Ebazhanov commented on accounting/accounting-quiz.md
> +> [Reference](https://www.investopedia.com/ask/answers/032515/what-difference-between-variable-cost-and-fixed-cost-economics.asp)
```suggestion
[Reference](https://www.investopedia.com/ask/answers/032515/what-difference-between-variable-cost-and-fixed-cost-economics.asp)
```

2022-10-10 20:05 UTC, Ebazhanov commented on accounting/accounting-quiz.md
> +> [Reference](https://qsstudy.com/segment-margin-differs-contribution-margin-explain/)
```suggestion
[Reference](https://qsstudy.com/segment-margin-differs-contribution-margin-explain/)
```

2022-10-11 06:30 UTC, victorwlin commented
I believe this is the intention, right? To move the reference out of the blockquote?

2022-10-11 07:03 UTC, Ebazhanov commented
> I believe this is the intention, right? To move the reference out of the blockquote?

yes with this `[]()` the link become active, you can find more examples in other quizes, thanks for updates

2022-10-11 07:04 UTC, Ebazhanov approved these changes
LTGM, thank you @victorwlin 👍

2022-10-11 07:04 UTC, merged