Create seo-quiz.md
Ebazhanov/linkedin-skill-assessments-quizzes pull request #4806
Opened 2022-10-16 09:28 UTC by varunsharma6956

2022-10-17 08:19 UTC, auchynnikau commented on seo-learning/seo-quiz.md
> +Answer:- (A)
Would be great to keep following common style guide for answers using checkbox markdown format. You can look trow how it was implemented in other `quiz.md` files.

2022-10-17 08:24 UTC, auchynnikau commented on seo-learning/seo-quiz.md
> +Search Engine Optimization(SEO)
Can you update main table in `README.md` file by including SEO quiz and providing link on it?

2022-10-17 19:54 UTC, Ebazhanov requested changes
Thank you @varunsharma6956 great job, could you double check if your question already exist in this file: https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/seo/search-engine-optimization-quiz.md

2022-10-18 01:51 UTC, varunsharma6956 commented
Ok sure

2022-10-18 02:14 UTC, varunsharma6956 commented
Sir my questions and answers doesn't exist on this  link wnich is

https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/seo/search-engine-optimization-quiz.md

Can you please approve my PR sir and merge it.

2022-10-18 06:25 UTC, shar2040 commented
yes sir i double checked mine questions and answers are different one from the link you gave sir can you merge it and approve

2022-10-18 06:33 UTC, Ebazhanov commented
> yes sir i double checked mine questions and answers are different one from the link you gave sir can you merge it and approve

@varunsharma6956 well what I mean, you have to not only compare but use the same file and not create your own. Please follow the formatting in already existing quizzes and add your new question accordingly. Thanks

2022-10-18 06:36 UTC, varunsharma6956 commented
Ok sir but mine questions and answers I have made of seo not taken from
there . If possible merge it

2022-10-18 06:37 UTC, shar2040 commented
i also used same seo file

2022-10-18 06:47 UTC, varunsharma6956 commented
sir I have used same file of seo which you told now and added mine in it, now can you see

2022-10-18 07:03 UTC, Ebazhanov commented
> sir I have used same file of seo which you told now and added mine in it, now can you see

pls double check your questions should inside https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/seo/search-engine-optimization-quiz.md

2022-10-18 08:08 UTC, varunsharma6956 commented
I have created sir seo-quiz.md inside seo folder inside that , can you
approve pr and approve it I have checked it and inside seo-quiz.md mine 19
questions there with answers

2022-10-18 08:14 UTC, Ebazhanov commented
> I have created sir seo-quiz.md inside seo folder inside that , can you approve pr and approve it I have checked it and inside seo-quiz.md mine 19 questions there with answers

thank you @varunsharma6956 for your effort but it does not work like this, I would prefer to keep everything in one file. And not create several. By the end it will bring complexity. Can you merge it in main file please or I can do it. Please let me know if you need any help. I still believe we can have your new questions here 👍

2022-10-18 08:19 UTC, varunsharma6956 commented
Sir can you convinced file and merge it.

2022-10-18 12:23 UTC, shar2040 commented
Sir can you put into folder and merge file and  accept pr

2022-10-18 12:27 UTC, Ebazhanov commented
> Sir can you put into folder and merge file and accept pr

will do, please give me some time I will create PR and assign you for review!

2022-10-18 15:22 UTC, auchynnikau commented
> Sir can you put into folder and merge file and accept pr

@shar2040 if you want, you can invite me to collaborate and I can help you to do it within you PR

2022-10-19 08:15 UTC, auchynnikau commented
> Sir can you put into folder and merge file and accept pr

@shar2040 if you want, you can invite me as a collaborator to your repo and I'll help you to finish this issue within your PR

2022-10-19 08:21 UTC, closed without merging