Added a new Question
Ebazhanov/linkedin-skill-assessments-quizzes pull request #4815
Opened 2022-10-16 10:35 UTC by gauravshukla2203

I am contributing here a new question in c++.md. If you are merging this PR , then please give it the tag of Hacktoberfest-accepted, as I have contributed this under Hacktoberfest 2022

2022-10-17 20:01 UTC, Ebazhanov requested changes
merge conflicts

2022-10-18 15:58 UTC, auchynnikau commented on c++/c++quiz.md
> +- [ ] print("Hello World");
```suggestion
- [ ] print("Hello World");
```

2022-10-18 18:03 UTC, Ebazhanov commented
@gauravshukla2203 ping

2022-10-25 07:29 UTC, Ebazhanov commented
@gauravshukla2203 ping

2022-11-05 11:51 UTC, Ebazhanov commented
@gauravshukla2203 your changes was merged via https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/5084

2022-11-05 11:51 UTC, closed without merging