Updated java file
Ebazhanov/linkedin-skill-assessments-quizzes pull request #4838
Opened 2022-10-17 14:47 UTC by AdityaShaw1

2022-10-17 14:48 UTC, AdityaShaw1 commented
i have created a pull request kindly pls review it

2022-10-17 20:14 UTC, Ebazhanov requested changes
Thank you @AdityaShaw1, could you please resolve merge conflicts before

2022-10-18 15:57 UTC, auchynnikau requested changes

2022-10-18 15:57 UTC, auchynnikau commented on java/java-quiz.md
> +#### Q 151. Which command will run a FrogSounds app that someone emailed to you as a jar?
```suggestion
#### Q151. Which command will run a FrogSounds app that someone emailed to you as a jar?
```

2022-10-18 18:05 UTC, Ebazhanov commented
@AdityaShaw1  ping

2022-10-18 18:07 UTC, closed without merging

2022-10-18 18:07 UTC, AdityaShaw1 commented
I will complete it by tmrw morning pls give me sometime

2022-10-18 18:13 UTC, Ebazhanov commented
no problem, take your time!