100. Which is default user in Ec2 Linux-red hat
Ebazhanov/linkedin-skill-assessments-quizzes pull request #4844
Opened 2022-10-17 17:11 UTC by chandolakul

100. Which is default user in Ec2 Linux-red hat/amazon.

2022-10-17 18:34 UTC, auchynnikau commented on aws/aws-quiz.md
> +- [ ] Create a IAM user for the new developer. Manually assign policies to the new IAM user acunt.
The initial word was correct, we don't need to change it. Please, fix this typo.

```suggestion
- [ ] Create a IAM user for the new developer. Manually assign policies to the new IAM user account.
```

2022-10-17 18:35 UTC, auchynnikau requested changes

2022-10-17 18:35 UTC, auchynnikau commented on aws/aws-quiz.md
> +- [ ] Create a IAM user for the new developer. Manually assign policies to the new IAM user acunt.
The initial word was correct, we don't need to change it. Please, fix this typo.

```suggestion
- [ ] Create a IAM user for the new developer. Manually assign policies to the new IAM user account.
```

2022-10-17 20:16 UTC, Ebazhanov requested changes
@chandolakul thanks for your PR, pls review comments

2022-10-18 05:14 UTC, chandolakul commented
@Ebazhanov Resolved Conflicts, Please approve the pull request and Kindly add the hacktoberfest-accepted label in this PR.

2022-10-18 05:45 UTC, Ebazhanov commented
> @Ebazhanov Resolved Conflicts, Please approve the pull request and Kindly add the hacktoberfest-accepted label in this PR.

what about an other comments, could you pls also fix typos, thanks

2022-10-18 05:53 UTC, Ebazhanov approved these changes
LGTM, 👍

2022-10-18 05:53 UTC, merged

2022-10-18 05:57 UTC, chandolakul commented
@Ebazhanov  --- Typo error fixed now..