Add a new Question
Ebazhanov/linkedin-skill-assessments-quizzes pull request #4846
Opened 2022-10-17 17:27 UTC by dazzle-sah

@Ebazhanov I have added a new question in Linux Section.
If you are merging this PR , then please give it the tag of Hacktoberfest-accepted, as I have contributed this as a part of Hacktoberfest 2022.

2022-10-17 20:17 UTC, Ebazhanov requested changes
merge conflicts

2022-10-18 15:54 UTC, auchynnikau commented on html/html-quiz.md
> +- [ ] Return the position of the first found occurrence of content inside a string
Your changes are duplicate each other. Please, check your PR #4843 it has 3 the same files with the same changes. Please split it, it's a good practice to create new PR for each topic.

2022-10-18 18:07 UTC, Ebazhanov commented
@dazzle-sah ping

2022-10-19 20:49 UTC, artemu78 commented on linux/linux-assessment.md
> +#### Q96. Which of these do NOT constitute as a default part of the email system of Red Hat Linux?
How is this related to HTML? Looks like it is a good question, but not really fit for HTML quiz.

2022-10-19 20:52 UTC, artemu78 commented on python/python-quiz.md
> +#### Q159. Which collection is ordered, changeable, and allows duplicate members?
It brakes questions number sequence, may be it worth to add question as a last, and simply increment number.  
Or you could change numbers of all next questions after this one.

2022-10-25 07:30 UTC, Ebazhanov commented
@dazzle-sah pls fix merge conflicts, thx

2022-11-04 18:26 UTC, auchynnikau commented on php/php-quiz.md
> +#### Q93. Which superglobal variable holds information about headers, paths, and script locations?
This question is already exist.

2022-11-05 11:51 UTC, Ebazhanov commented
@dazzle-sah your changes was merged via https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/5084

2022-11-05 11:51 UTC, closed without merging