Added new HTML Question
Ebazhanov/linkedin-skill-assessments-quizzes pull request #4950
Opened 2022-10-20 14:00 UTC by MakendranG

Added new HTML Question Q114 to Q116

2022-10-20 14:00 UTC, MakendranG commented
This is with reference to the issue https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/issues/4949

I have added the below details in this file.

Added new HTML Question Q114 to Q116

Kindly add `hacktoberfest-accepted` label in this PR

2022-10-20 18:29 UTC, artemu78 commented on html/html-quiz.md
> +
```suggestion

[Source](https://www.w3.org/TR/2011/WD-html-markup-20110113/syntax.html#syntax-elements)

```

2022-10-20 18:31 UTC, artemu78 commented on html/html-quiz.md
> +
```suggestion
[Source](https://www.w3schools.com/tags/att_label_for.asp)

```

2022-10-20 18:32 UTC, artemu78 commented on html/html-quiz.md
> +
```suggestion
```

2022-10-20 18:33 UTC, artemu78 commented on html/html-quiz.md
> +
```suggestion

[Source](https://www.w3schools.com/html/html_headings.asp)
```

2022-10-20 21:48 UTC, Ebazhanov requested changes
@MakendranG could you pls review comments, thanks

2022-10-21 01:10 UTC, MakendranG commented
@Ebazhanov 

Changes have been reviewed and it is been commited

2022-10-21 05:53 UTC, Ebazhanov approved these changes
LGTM 👍

2022-10-21 05:53 UTC, merged