Removed duplicate question in git-quiz.md
Ebazhanov/linkedin-skill-assessments-quizzes pull request #5870
Opened 2023-06-22 19:58 UTC by eddiestefanescu

## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ ] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [x] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

2023-06-22 20:02 UTC, eddiestefanescu commented
I removed Question 133 which was a duplicate of Question 26 (which has been corrected previously). In addition to being a duplicate, Q133 also was showing the wrong answer, making it very confusing for users.

2023-06-23 07:36 UTC, Ebazhanov requested changes
pls do clean up before we merge, thanks

2023-06-23 07:36 UTC, Ebazhanov commented on git/git-quiz.md
> +<<<<<<< HEAD
```suggestion
<<<<<<< HEAD
```
please remove

2023-06-23 07:36 UTC, Ebazhanov commented on git/git-quiz.md
> +=======
```suggestion

```

2023-06-23 07:36 UTC, Ebazhanov commented on git/git-quiz.md
> +>>>>>>> eabf07401dca2192893b1880e838ef587e743801
```suggestion
```

2023-06-23 17:24 UTC, eddiestefanescu commented
I got it... it's long overdue. I'll take care of it this weekend. I'll close the PR for now and resubmit it later.

2023-06-23 17:24 UTC, closed without merging