Updated kotlin-quiz.md
Ebazhanov/linkedin-skill-assessments-quizzes pull request #6717
Opened 2023-10-23 17:28 UTC by AckermanLevi1

## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ ] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [x] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

2023-10-23 18:36 UTC, haxkd requested changes

2023-10-23 18:36 UTC, haxkd commented on kotlin/kotlin-quiz.md
>  [reference](https://kotlinlang.org/docs/interfaces.html)
put reference before the Q114

2023-10-23 19:49 UTC, AckermanLevi1 commented on kotlin/kotlin-quiz.md
>  [reference](https://kotlinlang.org/docs/interfaces.html)
@haxkd reference is added, please check

2023-10-24 05:59 UTC, Ebazhanov approved these changes
Thank you @AckermanLevi1 👍

2023-10-24 05:59 UTC, merged