Updated Readme
Ebazhanov/linkedin-skill-assessments-quizzes pull request #6780
Opened 2023-10-24 17:31 UTC by Sumitwarrior7

## PR Checklist

### DOD

- [X] I have made small correction/improvements

### Changes / Instructions

_Updated Readme_

2023-10-24 19:17 UTC, Sumitwarrior7 commented
@Ebazhanov Sir you can merge this pr, cuz now it doesn't have any conflicts

2023-10-24 19:18 UTC, Sumitwarrior7 commented
@Ebazhanov Sir you can merge this pr, cuz now it doesn't have any conflicts

2023-10-24 19:34 UTC, Ebazhanov requested changes
🤔 🚬

2023-10-24 19:35 UTC, Ebazhanov commented on css/css-quiz.md
> +                                                                                              ``````````````````
if possible please remove this inconsistence, i mean this bulshit ```````````````````` .

thank you in advance!

2023-10-25 05:15 UTC, Sumitwarrior7 commented
Conflicting CSS file has been resolved now, you can check and merge

2023-10-25 05:20 UTC, Ebazhanov approved these changes
Thanks a lot, great job @Sumitwarrior7 👍

2023-10-25 05:20 UTC, merged