added 2 questions in html
Ebazhanov/linkedin-skill-assessments-quizzes pull request #6852
Opened 2023-10-28 06:26 UTC by achuehuehue

## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ ] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

2023-10-28 17:33 UTC, haxkd requested changes

2023-10-28 17:33 UTC, haxkd commented on html/html-quiz.md
> +- [ ] <ul>
mark the answer too

2023-10-28 17:34 UTC, haxkd commented
@achuehuehue resolve merge conflict

2023-10-28 17:41 UTC, achuehuehue commented on html/html-quiz.md
> +- [ ] <ul>
marked

2023-10-28 17:42 UTC, haxkd commented on html/html-quiz.md
> +- [ ] <ul>
Resolve merge conflict

2023-10-29 08:03 UTC, Ebazhanov approved these changes
LGTM, thank you @achuehuehue 👍

2023-10-29 08:03 UTC, merged